version: "3.9"
services:
  relationscrud-core:
    build: .
    ports:
      - "3000:3000"
    depends_on: 
      - relational_db
      - graph_db

  relational_db:
    image: postgres
    restart: unless-stopped
    ports: 
      - ${RELATIONAL_DB_PORT}:${RELATIONAL_DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${RELATIONAL_DB_PASSWORD}
      POSTGRES_USER: ${RELATIONAL_DB_USERNAME}
      POSTGRES_DB: ${RELATIONAL_DB_DATABASENAME}
      CONNECTION_STRING: "postgresql://${RELATIONAL_DB_USERNAME}:${RELATIONAL_DB_PASSWORD}@db:${RELATIONAL_DB_PORT}/${RELATIONAL_DB_DATABASENAME}"

  graph_db:
    image: neo4j:community
    restart: unless-stopped
    ports: 
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: ${GRAPH_DB_USERNAME}/${GRAPH_DB_PASSWORD}

